# This is docker-compose.yml file 
#
version: "3.8"

services:
  pr-preview:
    build: .
    container_name: pr-preview-${BRANCH_NAME}
    ports:
      - "5000:5000"
      - "${APP_PORT}:5000"
    environment:
      - BRANCH_NAME=${BRANCH_NAME}


# End
