
#
name: PR Preview Deployment


on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  deploy:
    runs-on: ubuntu-latest

  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "SSH Connection Successful!"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/pr-preview
            export BRANCH_NAME=${{ github.head_ref }}
            docker-compose up --build -d


      - name: Set up Docker Build
        run: |
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Build and Run the Docker Container
        run: |
          docker-compose up -d

      - name: Show Running Containers
        run: docker ps

# End 
